sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

asdoria_bulk_edit:
    resource: "@AsdoriaSyliusBulkEditPlugin/config/routing.yaml"


admin_product_variant_flag:
    path: api/v2/admin/product-variants/flag
    controller: App\Controller\Admin\ProductVariantFlagController::flagProductVariant
    methods: [POST]

admin_image_upload:
    path: /api/v2/admin/images/upload
    controller: App\Controller\Admin\ImageUploadController::uploadImage
    methods: [POST]

api_shop_upload_image:
    path: /api/v2/shop/upload-image
    controller: App\Controller\Shop\ImageUploadController::uploadImage
    methods: [POST]

# config/routes.yaml
odiseo_sylius_banner_plugin_admin:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/admin.yaml"
    prefix: /admin

odiseo_sylius_banner_plugin_shop:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}/banners
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$


product_images_by_category:
    path: /product/images/by-category/{taxonCode}
    controller: App\Controller\ProductController::showProductImagesByTaxonCode
    requirements:
        taxonCode: '[a-zA-Z0-9\-]+'  # Optionnel : tu peux d√©finir un pattern pour categorySlug
